builds:
  - id: linux-amd64-build
    binary: ax
    goos:
      - linux
    goarch:
      - amd64
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    env: &build-env
      - CGO_ENABLED=0
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'
      -X main.Version={{.Version}}

  - id: linux-arm64-build
    binary: ax
    goos:
      - linux
    goarch:
      - arm64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags

  - id: darwin-build
    binary: ax
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags

universal_binaries:
- id: darwin-build
- replace: true

archives:
  - id: default-archive
    builds:
      - linux-amd64-build
      - linux-arm64-build
      - darwin-build
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- if eq .Os "darwin" -}}
      macOS_{{- else -}}{{ .Os }}_{{- end -}}
      {{- if eq .Arch "amd64" -}}x86_64{{- else if eq .Arch "all" -}}
      universal{{- else -}}{{ .Arch }}{{- end -}}
      {{- with .Arm }}v{{ . }}{{ end -}}
      {{- with .Mips }}_{{ . }}{{ end -}}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}

brews:
  - name: axolotl

    repository:
      owner: SunwolfEngineering
      name: homebrew-tap

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: "https://github.com/SunwolfEngineering/axolotl/"

    description: "A helper utility for switching AWS profiles in subshells."

    # SPDX identifier of the license.
    license: "GPL-3.0-or-later"

    dependencies:
      - name: gimme-aws-creds

    test: |
      system "#{bin}/ax --version"
